{% set name = "xtensor-julia" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/xtensor-julia/archive/{{ version }}.tar.gz
  sha256: 1555c5f58eb23eaa6223727baaddc47258e2612786cd8e446be31c2ec93f777e

build:
  number: 0
  # Julia and libcxxwrap-julia have not been packaged for conda on Windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - xtl >=0.7.4,<0.8
    - xtensor >=0.24.0,<0.25
    - libcxxwrap-julia >=0.8.3,<0.9
  run:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-julia  # [unix]
    - test -f ${PREFIX}/include/xtensor-julia/jlarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-julia\jlarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-julia\xtensor-juliaConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-julia\xtensor-juliaConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://xtensor-julia.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Julia bindings for the xtensor C++ multi-dimensional array library.
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor-julia.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-julia

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
    - conda-forge/xtensor
